### ISSUE TITLE
Support for ACL removal

### ISSUE THREAD

**Issue by bernardoVale** [banzaicloud/koperator#135]
**Is your feature request related to a problem? Please describe.**
Yes, currently, the operator can only append permissions.

**Describe the solution you'd like to see**
The reconciliation of a user should also remove ACLs if the new version of the `KafkaUser` has dropped some grants.

**Additional context**
https://github.com/banzaicloud/kafka-operator/blob/master/controllers/kafkauser_controller.go#L217

**Comment by baluchicken** [comment]
Closing this since there is no plan to add more extended ACL support for the koperator.
