### ISSUE TITLE
Vault configuration assuming defaults

### ISSUE THREAD

**Issue by evilezh** [banzaicloud/koperator#290]
Another non-configurable this is kv storage mounted on /secret
We have couple scenarios ... 
if we use common secret storage then I would usually authorize path within storage e.g. /secret/kafka-oprator. Then I would need to configure it.
Option two - would be create new kv storage for kafka operator ... but that also is not possible.

This ticket and previous leads to idea - that I need dedicated vault instance to run this operator, which is most use cases would not be possible.

On separate note, there is "must have" configuration option in helm chart of operator: 
certManager: 
  namespace: some-namspace

As I figured out - it has nothing to do with cert-manager, but your kafka will be installed in that namespace. A bit misleading info.

**Comment by baluchicken** [comment]
Vault configuration is no longer supported as a PKI. Cert-manager or K8sCertificateSigning requests are the preferable ones so closing this since this is not relevant any more.
