### ISSUE TITLE
Support all ACL operation types

### ISSUE THREAD

**Issue by SapientGuardian** [banzaicloud/koperator#319]
**Is your feature request related to a problem? Please describe.**
I am trying to set up [Kafdrop](https://github.com/obsidiandynamics/kafdrop). It worked great when I had no authentication on my Kafka cluster, but with ACLs enabled it throws `org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [Topic authorization failed.]` because I am unable to grant its user sufficient access to the cluster.

Configuring the user with the following was insufficient:
```
  topicGrants:
    - topicName: '*'
      accessType: read
```

**Describe the solution you'd like to see**
I think what's missing is the ability to set the `DESCRIBE_CONFIGS` operation type on the topic-level ACL, but it could also be that I need to be able to set this at the Cluster resource, which kafka-operator doesn't seem to support either.

**Describe alternatives you've considered**
Adding the user as a super user may be a sufficient workaround, but is not ideal in cases where you want to restrict write access.

I also tried using kafka-acls.sh to manually set the ACL, but I couldn't figure out how to use the tool correctly.

**Additional context**
https://docs.confluent.io/current/kafka/authorization.html shows a far more expansive picture of applicable ACL options than is currently supported.

**Comment by baluchicken** [comment]
There is no intent to support more ACL's in the KOperator so closing this. Of course PR's are always welcome.
