### ISSUE TITLE
Ability to set a minimum number of brokers in clusters and avoid accidental downscale below this limit

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/koperator#329]
**Is your feature request related to a problem? Please describe.**
To avoid accidental data loss I find useful to have a hard check on minimum number of brokers in cluster and avoid accidental downscale.

**Describe the solution you'd like to see**
A config at KafkaCluster CR level to set the min cluster size.

**Describe alternatives you've considered**
N/A

**Comment by stoader** [comment]
By accidental downscale you mean manual downscale or the auto upscale.downscale triggered by alerts? For the later limits can be enforced through https://github.com/banzaicloud/kafka-operator/blob/master/api/v1beta1/kafkacluster_types.go#L210

**Comment by amuraru** [comment]
The former Seba. I know the alert based auto scaling already has limits but was thinking to promote those limits globally for all operations that involve scaling of cluster

**Comment by stoader** [comment]
@amuraru do you think this feature is still needed/useful to have in koperator? Currently, the user can not downscale the cluster below the highest replication factor number as CC will return with an error when koperator invokes the `remove_broker` task (provided that the user enabled at least the `RackAwareDistributionGoal` for the cluster).

E.g. if there is at least a topic with RF 3 than when the user downscales the cluster to 2 broker the `remove_broker` in CC will return something like `HTTP/1.1 500 Internal Server Error.....[RackAwareDistributionGoal] Cannot remove Replica...Add at least 1 broker. Add at least 1 broker.`

**Comment by amuraru** [comment]
Good point on the CC guard @stoader!
I don't feel strong for this - we can close it and reopen if really needed in the future!
