### ISSUE TITLE
Support for transaction id ACLs

### ISSUE THREAD

**Issue by qbast** [banzaicloud/koperator#348]
**Is your feature request related to a problem? Please describe.**

Using transactional producers requires authorising transactional.id in Kafka. Unfortunately there is no way of adding required ACLs using KafkaUser resource - it only supports topic-level acls.

**Describe the solution you'd like to see**

KafkaUser CRD should be extended to add a list of authorised transactional ids, similar to topicGrants. The only operations supported are WRITE and DESCRIBE, so it there is no need to specify accessType  in CRD.
For example:
```
 - transactionalIdGrants:
   - transactionalId: txid
     patternType: literal
```

This would create two ACLs for the user: 
```
 User:CN=XXX,O=cert-manager,TransactionalId,LITERAL,txid,Describe,Allow,*
 User:CN=XXX,O=cert-manager,TransactionalId,LITERAL,txid,Write,Allow,*
```
**Describe alternatives you've considered**

Simpler solution would be to automatically create wildcard ACLs if a user has any topic write permissions. Similar to how any kafka user with read permissions gets automatic 'Group','*','Read' ACL.
```
User:CN=XXX,O=cert-manager,TransactionalId,LITERAL,*,Describe,Allow,*
User:CN=XXX,O=cert-manager,TransactionalId,LITERAL,*,Write,Allow,*
```

**Comment by baluchicken** [comment]
There are not intention to support more ACLs with Koperator so closing this.
