### ISSUE TITLE
Idempotent producer does not work

### ISSUE THREAD

**Issue by qbast** [banzaicloud/koperator#365]
**Describe the bug**
Idempotent producer fails with "org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed" error.

**Steps to reproduce the issue:**
Create a new cluster, a topic and a KafkaUser. Give the new user write access to the topic.
Try sending a message to the topic using idempotent producer. An authorization exception will be thrown.

**Expected behavior**
I would expect that giving write access to a topic also allows idempotent producer to work.

**Additional context**
I realise that idempotent producer also requires IDEMPOTENT_WRITE cluster-level ACL, but I think that if an user is authorised to write to any topic, this ACL should be added automatically by the operator.

**Comment by baluchicken** [comment]
Closing this because there is no intention to add more ACL settings to the koperator.
