### ISSUE TITLE
Finish cleanup of cruise control scaler

### ISSUE THREAD

**Issue by lukemassa** [banzaicloud/koperator#367]
**Is your feature request related to a problem? Please describe.**
When implementing https://github.com/banzaicloud/kafka-operator/pull/361, I offered to refactor `pkg/scale/scale.go` to use methods instead of functions, since all of the functions in that method took, among others, the exact same four args. 

While the change definitely cleaned up `scale.go`, it left client code a little something to be desired, especially `controllers/cruisecontroltask_controller.go`, where I ended up creating and then using just once instances of the `CruiseControlScaler` struct.

**Describe the solution you'd like to see**
I'm not exactly sure, some thought I have are
1. Leave it as is; it's not that bad just a little awkward
2. Helper function on KafkaCluster to get a `CruiseControlScaler`
3. Remove the `CruiseControlScaler` and make methods in `scale.go` actually be on a `KafkaCluster`

**Comment by baluchicken** [comment]
This will be taken care of as part of the refactor process so closing this one.
