### ISSUE TITLE
request to add provision to set securityContext in the CRD for pods created by operator

### ISSUE THREAD

**Issue by priyavj08** [banzaicloud/koperator#430]
**Is your feature request related to a problem? Please describe.**
I want to be able to set securityContext so pods can be set up to run as NonRoot for security reasons

**Describe the solution you'd like to see**
ability to set securityContext in CRD for different pods

**Describe alternatives you've considered**

**Additional context**

**Comment by priyavj08** [comment]
@baluchicken hi, when will this be taken up?

thanks
priya

**Comment by vassilvk** [comment]
@priyavj08, as a workaround, you can create a [KubeMod](http://github.com/kubemod/kubemod) `ModRule` to customize the pods generated by the operator and inject your own `securityContext` section.

See KubeMod's [Getting started](https://github.com/kubemod/kubemod#getting-started) section as an example of doing just that.

**Comment by baluchicken** [comment]
This one is already implemented with https://github.com/banzaicloud/koperator/pull/527 so closing this.
