### ISSUE TITLE
Provide automated canary deployment and analysis support when applying changes to running kafka cluster

### ISSUE THREAD

**Issue by vasilievip** [banzaicloud/koperator#455]
1. We are using netflix kayenta as service to automatically analyze canary deployments
2. When making changes to running kafka cluster we want to avoid downtime if changes are breaking cluster

- https://www.infoq.com/presentations/canary-analysis-deployment-pattern/
- https://github.com/spinnaker/kayenta
- https://www.youtube.com/watch?v=3xQm7CsR0ww

So, MVP here - when applying changes operator should support canary deployment and we should have ability to programmatically continue or rollback deployment via deployment pipeline based on data from canary analysis which pipeline will fetch from kayenta 
 
![Screen Shot 2020-09-01 at 3 17 23 PM](https://user-images.githubusercontent.com/1525698/91850467-4bc14c80-ec66-11ea-8955-58091a2dcd1b.png)

https://github.com/helm/helm/issues/6572
https://github.com/aerospike/aerospike-kubernetes-operator/issues/14
https://github.com/elastic/cloud-on-k8s/issues/3479#issuecomment-686588054

**Comment by baluchicken** [comment]
This issue is stale for a while, closing this, but PR's are always welcome.
