### ISSUE TITLE
Operator dead locks during rolling upgrade if another pod is killed

### ISSUE THREAD

**Issue by matt-christiansen-exa** [banzaicloud/koperator#533]
**Describe the bug**

I have seen this happen a few times if we have a relatively large cluster, say 24 nodes, and a rolling update is started on that cluster if any other pod down the line is also restarted that pod never gets replaced and the rolling update deadlocks. I can make it progress forward if I start killing the pod its waiting on, its like the reconcile loop happens replaces the missing pods which allows the updated pod to come on line then it progress forward just fine. 

I believe the main problem is it waits for all topics to not be under replicated as [here](https://github.com/banzaicloud/kafka-operator/blob/e39e4de1d4a91fc6ec337e3a573af10eba43c700/pkg/resources/kafka/kafka.go#L625) which I agree with. Likely we need to keep the reconciliation loop going, maybe starting the pods with the existing config while the rolling upgrade happens. I'm not entirely sure of the best possible resolution here. 

One possible solution I have thought of is maybe a timeout waiting for it to be in sync, allowing the loop to replace the missing pods and try the upgrade again. 

**Steps to reproduce the issue:**
Create a cluster, I think it would work with any size cluster but its easier to do it with larger clusters. Trigger a rolling upgrade (change a config property or the version of kafka) and once the CR is in that state delete one of the kafka brokers that's further down the path, like if you have 5 delete broker 4. At that point it should be stuck on waiting for what ever pod its on for all replicas to be in sync. Delete what ever broker its on (a bit of guess work) and watch it replace broker 4 as well as the one its currently upgrading. 

**Expected behavior**
That rolling upgrade doesn't block downstream pod restarts and can proceed 

**Screenshots**

**Additional context**
Add any other context about the problem like release numberm version, branch, etc.

**Comment by amuraru** [comment]
@matt-christiansen-exa I think `rollingUpgradeConfig.failureThreshold` can help in your case  https://github.com/banzaicloud/kafka-operator/blob/1f68f0a0c05dc53cce9d140e427ea67a937c9dfc/config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml#L5710-L5718

It controls the max number of failures the rolling restart tolerates. If you increase that the operator should be able to skip a failing broker and continuing the procedure.

**Comment by baluchicken** [comment]
Closing this since a fix just got merged. Please reopen it in case of reoccurrence.
