### ISSUE TITLE
CruiseControlConfig Configuration enhancement

### ISSUE THREAD

**Issue by lengrongfu** [banzaicloud/koperator#537]
**Is your feature request related to a problem? Please describe.**
         1、Add Service configuration when creating CC, such as Server type.
         2、Add data persistence when creating cc deployment, and add dynamic PVC creation logic.

**Comment by baluchicken** [comment]
Thanks for opening this issue @lengrongfu. Can you please elaborate more on these? Can you please share your use case so we can see the bigger picture?

**Comment by lengrongfu** [comment]
Thank you for your reply @baluchicken 。
- Regarding the first point, add the `Service` configuration. After the `cc` service is created using `cr`, the service type cannot be modified, and `service annotations` cannot be added. After the server `type` can be modified, it can be changed to `Lb`, and then we can access `cc-ui` web
- Regarding the second point, I have no application scenario for the time being.
