### ISSUE TITLE
ephemeral  volume for broker-data

### ISSUE THREAD

**Issue by metbog** [banzaicloud/koperator#595]
Hi guys,

Could you please add ephemeral volume support for broker data (storage)? 
We just need a possibility to  set /kafka-logs as emptydir and don't use pvc

We need it for fast deployment and testing of our qualitygate flows. 

Thanks

**Comment by baluchicken** [comment]
Hi, can you please give more details what is the business value and use case behind this feature request? For testing we use Minikube, Kind, DockerForMac all of these supports allocating PVC through a default storageclass.

**Comment by metbog** [comment]
We use PVC on preprod, prod, but we don't need it for a flow of qualitygates. There we have more than 100 qualitygates per  day. So, we just don't need to use PVC for it

**Comment by morphalus** [comment]
Hi, just my two cents to say that i'm in the case where i would like to use an emptyDir with local SSD behind (GKE).

A more flexible storage declaration would be great :)

**Comment by jgautheron** [comment]
Similar scenario here, we'd like to use local ssds in a raid setup, for cost reduction (up to 4x times cheaper than PD) and performance improvements (IOPS).

**Comment by stoader** [comment]
@metbog @morphalus @jgautheron trying to assess if https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes (which became stable in Kubernetes 1.23) would cover your use case? Note that ephemeral volumes are lost in case their owning Pod is restarted for whatever reason (this is true for emptyDir as well being recreated on Pod restarts)

**Comment by metbog** [comment]
> @metbog @morphalus @jgautheron trying to assess if https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes (which became stable in Kubernetes 1.23) would cover your use case? Note that ephemeral volumes are lost in case their owning Pod is restarted for whatever reason (this is true for emptyDir as well being recreated on Pod restarts)

yes, it definitely would cover my case

**Comment by stoader** [comment]
Just for my understanding in your case losing data is an issue. If a broker Pod is restarted for whatever reason (e.g. CPU / memory settings are changed in the pod spec) the ephemeral volume attached to it will be lost with all the topic partition data.

**Comment by metbog** [comment]
> Just for my understanding in your case losing data is an issue. If a broker Pod is restarted for whatever reason (e.g. CPU / memory settings are changed in the pod spec) the ephemeral volume attached to it will be lost with all the topic partition data.

We are going to use ephemeral volume only for qualitygate pipeline. Losing data is not critical for us in this case. QG can be just re-run if something goes wrong. We have big queue for QG per day and we don't want to be dependent by storage problem

**Comment by stoader** [comment]
@metbog the feature that supports `emptyDir` as Kafka storage has been added to `koperator`(see https://github.com/banzaicloud/koperator/blob/master/config/samples/banzaicloud_v1beta1_kafkacluster.yaml#L59-L61). This feature will be released with the next release. Until than you can try this feature from `master` branch.
