### ISSUE TITLE
Add support to set brokerGroup specific labels to kafka pods

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/koperator#605]
**Is your feature request related to a problem? Please describe.**

Currently the operator support setting kafka pods labels via `propagateLabels` field in the KafkaCluster spec. This way not only the pods but all the created resources will get the labels. 
In addition to that it would be useful to have the ability to set kafka pods labels specific for each brokerConfigurationGroup, i.e. `kafka_broker_group: group_name`
For our use-case this can be used in Prometheus monitoring to capture the group/az for each broker as a label.

**Describe the solution you'd like to see**

Add a new optional field to KafkaCluster spec: `brokerConfigGroups.<group>.brokerLabels` that's appended to the current list of pod labels when set.

**Describe alternatives you've considered**

Currently we are making use of `brokerConfigGroups.<group>.brokerAnnotations` but this needs additional manipulation in Prometheus ServiceMonitor definition to transform a pod annotation to a metric label.

**Comment by LukasSlouka** [comment]
Also useful with network policies

**Comment by panyuenlau** [comment]
Hey @amuraru @LukasSlouka, this has been added to the operator, see [this newly added section](https://github.com/banzaicloud/koperator/blob/master/config/samples/banzaicloud_v1beta1_kafkacluster.yaml#L60-L61) about how to configure the `kafkacluster` to set a group-specific label for the brokers
