### ISSUE TITLE
NodePort with external IP is not advertising on externalPort

### ISSUE THREAD

**Issue by sivarp** [banzaicloud/koperator#634]
**Describe the bug**
type NodePort with NodePortExternalIP exposes service in external IP and port allocated using externalStartingPort logic for the kafka cluster.
But the `advertised.listeners` is updated with `EXTERNAL://<external_IP>:<containerPort>` instead of `EXTERNAL://<external_IP>:<externalPort>`
This does not allow kafka client to connect with external IP and external port. Error trace below,
```
root@177937ac8185:/# /opt/kafka/bin/kafka-console-producer.sh --broker-list "10.36.15.58:30165" --topic tcdn_data
>hello
[2021-06-24 08:16:01,898] WARN [Producer clientId=console-producer] Connection to node 2 (/10.36.13.61:9094) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2021-06-24 08:16:02,168] WARN [Producer clientId=console-producer] Connection to node 1 (/10.36.12.214:9094) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2021-06-24 08:16:02,434] WARN [Producer clientId=console-producer] Connection to node 2 (/10.36.13.61:9094) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2021-06-24 08:16:02,701] WARN [Producer clientId=console-producer] Connection to node 1 (/10.36.12.214:9094) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2021-06-24 08:16:02,970] WARN [Producer clientId=console-producer] Connection to node 0 (/10.36.15.58:9094) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2021-06-24 08:16:03,236] WARN [Producer clientId=console-producer] Connection to node 1 (/10.36.12.214:9094) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2021-06-24 08:16:03,502] WARN [Producer clientId=console-producer] Connection to node 2 (/10.36.13.61:9094) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
root@177937ac8185:/#
root@177937ac8185:/# telnet 10.36.15.58 30165
Trying 10.36.15.58...
Connected to 10.36.15.58.
Escape character is '^]'.
^]
telnet> quit
```
from configmap for broker-0,
```
advertised.listeners=CONTROLLER://tskafka-0.kafka.svc.cluster.local:29093,EXTERNAL://10.36.15.58:9094,INTERNAL://tskafka-0.kafka.svc.cluster.local:29092
```

**Steps to reproduce the issue:**
apply https://github.com/banzaicloud/kafka-operator/blob/master/config/samples/simplekafkacluster-with-nodeport-external.yaml with external ip added in brokerConfig.
```
from machine with kafka installation,
/opt/kafka/bin/kafka-console-producer.sh --broker-list "<external_ip>:<nodePort>" --topic tcdn_data
```

**Expected behavior**
advertised.listeners should be updated with external port as in hostnameOverride case.With hostnameOverride, client is able to connect to the kafka broker.
from configmap for broker-0,
```
advertised.listeners=CONTROLLER://tskafka-0.kafka.svc.cluster.local:29093,EXTERNAL://tskafka-0.external1.kafka.dev:30165,INTERNAL://tskafka-0.kafka.svc.cluster.local:29092
```

NodePort with externalIP should update advertised.listeners with external port and it does not happen currently.
Expected:
```
advertised.listeners=CONTROLLER://tskafka-0.kafka.svc.cluster.local:29093,EXTERNAL://10.36.15.58:30165,INTERNAL://tskafka-0.kafka.svc.cluster.local:29092
```

**Comment by baluchicken** [comment]
Thanks for opening a ticket. The described behaviour is intended. If you take a closer look on the kubernetes documentation especially to external IPs https://kubernetes.io/docs/concepts/services-networking/service/#external-ips you can find out that if you are using external IPs for a given service all the traffic will be routed through the port instead of the nodeport.

**Comment by sivarp** [comment]
@baluchicken, Thanks for your response.
If that is the case, we are still unable to access the service using external_ip: port.
In the scenario shared above, 10.36.15.58:9094 is not working from kafka producer (external to k8s cluster).
Can you explain how it should be accessed externally?

**Comment by stoader** [comment]
@sivarp can you share you Kafka Cluster CR?

**Comment by sivarp** [comment]
[kafka-cr.zip](https://github.com/banzaicloud/kafka-operator/files/6763459/kafka-cr.zip)

@stoader attached the same.

**Comment by stoader** [comment]
Can you confirm if the IP addresses you provided under `nodePortExternalIP.external` match the public IP of your nodes ?

You can check that by running `kubectl get node -o wide`

**Comment by sivarp** [comment]
`kubectl get node -o wide` shows external ip as none for the nodes.

I'm using rancher to provision kubernetes cluster. From rancher cluster gui, able to see external ip/internal ip. 
![Screenshot from 2021-07-08 17-51-27](https://user-images.githubusercontent.com/5279191/124920899-73670b00-e015-11eb-8b6b-3d7209916c86.png)

Confirm that svc is exposed on the nodeport and telnet is working to the `external ip:nodePort`

**Comment by stoader** [comment]
I can see that the external IPs specified in your KafkaCluster CR are different from your node public IPs. In that case Kafka clients should connect to <external-ip-specified-in-kafkacluster-cr>:<container-port>.

This setup requires routing from <external-ip-specified-in-kafkacluster-cr> to the nodes of your Kubernetes cluster nodes to be enabled such that wen a Kafka client application connects to <external-ip-specified-in-kafkacluster-cr>:<container-port> packages to be routed to one of the nodes of your Kubernetes cluster.
See https://banzaicloud.com/blog/kafka-external-access/#nodeport-external-ip


Can you confirm that the appropriate rounting rules are setup for the external IPs you specified in the KafkaCluster CR?

**Comment by sivarp** [comment]
@stoader I've recreated the environment using script and hence, you can note that IP address has changed. (my bad, missed to share it earlier). Changes are updated in kafkaCluster CR already.

> This setup requires routing from <external-ip-specified-in-kafkacluster-cr> to the nodes of your Kubernetes cluster nodes to be enabled such that wen a Kafka client application connects to <external-ip-specified-in-kafkacluster-cr>:<container-port> packages to be routed to one of the nodes of your Kubernetes cluster.
Can you confirm that the appropriate rounting rules are setup for the external IPs you specified in the KafkaCluster CR?

yes, routing is working and am able to connect to the nodePort using the external IP from the kafka client machine. Meaning, in turn external IP routes to the node IP and connection established to nodePort. But, same results in connection refused for `<external-ip-specified-in-kafkacluster-cr>:<container-port>`.

**Comment by sivarp** [comment]
Environment details:
Openstack wallaby
Rancher 2.5.5

External IP for the node is floating ip assigned from openstack network.

**Comment by stoader** [comment]
Can you show your routing rules that forward traffic received on `10.36.15.58:9094`, `10.36.12.214:9094` and `10.36.13.61:9094` to the node's external IP (`10.36.13.79:9094`, `10.36.15.226:9094` and `10.36.15.181:9094`)?

Also, `kubectl get node -o wide` not showing external-ip may indicate that your K8s cluster may not be configured properly.


If you want to expose the kafka pod on node port than do not set external IP in `nodePortExternalIP.external` in your KafkaCluster CR.  In that case brokers will be advertised on "dynamic URL" which you can register in your DNS and point it to the external IP of the nodes that you see on the Rancher UI.

**Comment by baluchicken** [comment]
This issue is stale for a while please reopen if this issue still stands.
