### ISSUE TITLE
KafkaCluster: force termination

### ISSUE THREAD

**Issue by metbog** [banzaicloud/koperator#653]
Hello,

We have an issue like in: https://github.com/banzaicloud/koperator/issues/262

We need to remove namespace forcibly:
first we run helm3 for deleting charts:
`        if [[ $(kubectl get deployment -l app=helm -n "$StageName") ]]
            for release in $(helm3 ls --all --short -n "$StageName" || true); do
                helm3 del "$release" -n "$StageName"
            done
        fi`

then we use
`kubectl delete ns "$StageName" --ignore-not-found --now`

Sometime it happens when zookeeper is being deleted before kafkacluster and we get finalizer for kafkatopics.kafka.banzaicloud.io and it can't be removed
We don't need to save or keep any data, so we just need to "kill" it. 
Is there any way to delete forcibly kafkacluster? 
Can you add an option for this possibility?

**Comment by baluchicken** [comment]
Thanks for opening this @metbog.
The recommended way to delete a kafka cluster is the following:
- Delete kafka cluster CR and wait until it disappears 
- Delete helm chart releases operator and zookeeper operator
- Delete the namespaces
Unfortunately we are not aware of any tool which allows us to forcibly delete a k8s resource which has the finalizer.
