### ISSUE TITLE
Missing certificatesigningrequests Error in Kafka Operator v0.18.0

### ISSUE THREAD

**Issue by laukik85** [banzaicloud/koperator#656]
Tried to install Kafka Operator v0.18.0 in AKS environment and received following error.

E0831 23:41:54.208642       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.3/tools/cache/reflector.go:167: Failed to watch *v1.CertificateSigningRequest: failed to list
*v1.CertificateSigningRequest: certificatesigningrequests.certificates.k8s.io is forbidden: User "system:serviceaccount:kb:kafka-operator" cannot list resource "certificatesigningrequests" in API group "certificates.k8s.io" at the cluster scope

**Comment by bartam1** [comment]
Dear Laukik85!

Thank you for the information. We have already found that bug. Soon It willl be fixed.
