### ISSUE TITLE
Kafka cluster become unstable when enabling prometheus monitoring

### ISSUE THREAD

**Issue by bechhansen** [banzaicloud/koperator#659]
**Describe the bug**
We have a well operating Kafka cluster with topics deployed in our Kubernetes cluster, provisioned by the Banzai Cloud Operator.
When enabling prometheus monitoring by adding the kubernetes annotations as descried here, https://banzaicloud.com/docs/supertubes/kafka-operator/monitoring/, the cluster becomes unstable as one of the worker pods continuously terminate after ~30-40 seconds.
`
    brokerConfigGroups:
        default:
        brokerAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9020"
`

By looking at the operator logs, it looks like the operator is responsible for terminating the Kafka worker.
`{"level":"info","ts":"2021-09-01T12:07:54.771Z","logger":"controllers.KafkaCluster","msg":"terminated container for broker pod","Request.Namespace":"default/xxxx-xxxx-kafka","Request.Name":"xxxx-xxxx-kafka","component":"kafka","clusterName":"xxxx-xxxx-kafka","clusterNamespace":"default","kind":"*v1.Pod","pod":"xxxx-xxxx-kafka-0-7jpzc","brokerId":"0","containerName":"istio-proxy","exitCode":0,"reason":"Completed"}
{"level":"info","ts":"2021-09-01T12:07:54.771Z","logger":"controllers.KafkaCluster","msg":"terminated container for broker pod","Request.Namespace":"default/xxxx-xxxx-kafka","Request.Name":"xxxx-xxxx-kafka","component":"kafka","clusterName":"xxxx-xxxx-kafka","clusterNamespace":"default","kind":"*v1.Pod","pod":"xxxx-xxxx-kafka-0-7jpzc","brokerId":"0","containerName":"kafka","exitCode":0,"reason":"Completed"}
{"level":"info","ts":"2021-09-01T12:07:54.771Z","logger":"controllers.KafkaCluster","msg":"broker pod deleted","Request.Namespace":"default/xxxx-xxxx-kafka","Request.Name":"xxxx-xxxx-kafka","component":"kafka","clusterName":"xxxx-xxxx-kafka","clusterNamespace":"default","kind":"*v1.Pod","pod":"xxxx-xxxx-kafka-0-7jpzc","brokerId":"0"}
{"level":"info","ts":"2021-09-01T12:08:04.782Z","logger":"controllers.KafkaCluster","msg":"Kafka cluster state updated","Request.Namespace":"default/xxxx-xxxx-kafka","Request.Name":"xxxx-xxxx-kafka","component":"kafka","clusterName":"xxxx-xxxx-kafka","clusterNamespace":"default"}`

It looks like the Kafka pod is being gracefully terminated:
`[2021-09-01 13:51:52,817] INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-09-01 13:51:52,819] INFO [KafkaServer id=1] shutting down (kafka.server.KafkaServer)
[2021-09-01 13:51:52,821] INFO [KafkaServer id=1] Starting controlled shutdown (kafka.server.KafkaServer)
[2021-09-01 13:51:53,001] INFO [KafkaServer id=1] Controlled shutdown succeeded (kafka.server.KafkaServer)`

**Steps to reproduce the issue:**
- Start a Kafka cluster using the Banzai Cloud Operator.
- Observe the cluster to be stable
- Add the brokerAnnotations as described here: https://banzaicloud.com/docs/supertubes/kafka-operator/monitoring
-  Observe worker continuously restart

**Expected behavior**
I expect that the Kafka cluster would remain stable after adding the Kubernetes annotations.

**Screenshots**
![image](https://user-images.githubusercontent.com/426810/131669063-2ebf432b-adca-4bcf-aa25-d31b0237b751.png)

**Additional context**
The issue has been reproduced on version 0.16.1, 0.17.0 and 1.18.1
I have not be able to get a Cluster running using 0.18.0 because of this issue: https://github.com/banzaicloud/koperator/issues/658

Kubernetes: Kubernetes: k3s v1.19.7-k3s1

We see this issue even though there is no Prometheus pod deployed in the cluster, hence metrics scraping should not happen.

**Comment by bechhansen** [comment]
For the namespace where the Kafka cluster is deployed we are using automatically deployed Istio Sidecars.

When disabling the Istio Sidecar the problem stop and the Kafka cluster is stable. 

Disable Sidecar deployment:
brokerAnnotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/path: "/"
        prometheus.io/port: "9020"
        prometheus.io/scrape: "true"

I think maybe the issue here is that Istio terminates the Kafka node?

**Comment by baluchicken** [comment]
Hi @bechhansen thanks for opening this issue. 
To answer your questions I am not aware that Istio can terminate a Kafka broker.
My guess is you have an istio config problem which causes modification in the kafka broker pod spec created by the operator.
So the operator thinks that someone is trying to do some nasty stuff by editing the pods manually thus it just enforces the settings from the kafkacluster CR.

**Comment by bechhansen** [comment]
> Hi @bechhansen thanks for opening this issue.
> To answer your questions I am not aware that Istio can terminate a Kafka broker or a kubernetes pod.
> My guess is you have an istio config problem which causes modification in the kafka broker pod spec created by the operator.
> So the operator thinks that someone is trying to do some nasty stuff by editing the pods manually thus it just enforces the settings from the kafkacluster CR.

Interesting. The weird thing is that it is always only one single broker that are being terminated. The other pods of the Kafka cluster are stable. All I need to do to provoke this behavior is to add the 'prometheus.io/scrape: "true"' broker-annotation.

I have now reproduced the issue using https://github.com/banzaicloud/koperator/blob/master/config/samples/simplekafkacluster.yaml.

**Comment by stoader** [comment]
@bechhansen istio changes the `prometheus.io` annotations on the broker pod thus the pod spec will differ from what the operator generated. This triggers the operator to re-generate the pod spec which results in a pod restart.

Can you try adding `prometheus.istio.io/merge-metrics: "false"` to broker-annotation as well ?

**Comment by bechhansen** [comment]
> @bechhansen istio changes the `prometheus.io` annotations on the broker pod thus the pod spec will differ from what the operator generated. This triggers the operator to re-generate the pod spec which results in a pod restart.
> 
> Can you try adding `prometheus.istio.io/merge-metrics: "false"` to broker-annotation as well ?

Disabling 'merge-metrics' would probable solve the issue, I'll go try, but I would like to use that feature so I don't need to do additional Prometheus configuration.

Do you think the solution could be to not set the 'prometheus.io/xxxx' annotations but create ServiceMonitors instead?

**Comment by stoader** [comment]
Yes using service monitor would work as well.

**Comment by stoader** [comment]
I take it back. It won't work as istio would still modify the pod definition.

**Comment by stoader** [comment]
How about using `prometheus.istio.io/merge-metrics: "false"` and create a service monitor for the kafka metrics and a service monitor for the metrics provided by istio sidecar container. With service monitors you can scrape multiple containers in a pod separately.

**Comment by baluchicken** [comment]
Closing this since the questions was answered above.
