### ISSUE TITLE
Add support for liveness/readiness probes in kafka, envoy and cruisecontrol pods through Kafkacluster CR

### ISSUE THREAD

**Issue by raz08** [banzaicloud/koperator#672]
**Describe the bug**
I tried to add liveness and readiness probes to kafka cluster pods i.e. Kafka, Envoy and CruiseControl. But I don't see that provision to add these settings through Kafkacluster CR. Is probes supported?

**Comment by baluchicken** [comment]
Closing this on favor of #661
