### ISSUE TITLE
Sequence brokers ConfigMap update during cluster rolling upgrade

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/koperator#693]
**Is your feature request related to a problem? Please describe.**

Currently the brokers ConfigMaps (`<clusterName-config-<brokedId>`) are upgraded all at once once the cluster upgrade is started.
A better approach would be to have the ConfigMap updated with the new configuration on a per broker basis and executed in sync with the broker upgrade. This way, if for some reason the broker needs to be recovered it should be able to be restarted with the current running configuration and not a new one.

**Describe the solution you'd like to see**

Ensure broker ConfigMap is updated as part of the broker upgrade.

**Describe alternatives you've considered**

N/A

**Additional context**

This came up as part of the discussion on how to properly address https://github.com/banzaicloud/koperator/issues/533 and it's a pre-requisite for that

**Comment by stoader** [comment]
Closing this issue as after taking a closer look this is already the current behavior. The configmaps holding broker configuration are created broker-by-broker in the following loop: https://github.com/banzaicloud/koperator/blob/master/pkg/resources/kafka/kafka.go#L215
