### ISSUE TITLE
Snapshot broker configuration and restore if needed

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/koperator#694]
**Is your feature request related to a problem? Please describe.**

Currently if an broker ConfigMap object is accidentally deleted there are cases where the current running configuration cannot be restored. The only option for the operator may be to regenerate the broker config out of the KafkaCluster CR but that may not be always accurate: e.g. when cluster is being upgraded.

**Describe the solution you'd like to see**

The proposal here is to ensure the broker config map once generated and broker starting using it to be stored in KafkaCluster status subresource and used for recovery if needed.

**Comment by stoader** [comment]
@amuraru I wonder if https://github.com/banzaicloud/koperator/pull/824 covers this cases entirely or partially. If so we can close this ticket and create new ones with if any gap is found in the existing implementation that needs to be addressed.

cc @bartam1 @pregnor @hi-im-aren
