### ISSUE TITLE
Support for one-way TLS without client authentication

### ISSUE THREAD

**Issue by mahpatil** [banzaicloud/koperator#726]
**Is your feature request related to a problem? Please describe.**
We would like to setup one-way TLS without mutual authentication using this operator. However, it looks like currently ssl.client.auth is set to "required" by default in configmap.go whenever SSL config is specified. 

**Describe the solution you'd like to see**
It should be possible to set all possible values (required, requested, none) for  ssl.client.auth.

**Describe alternatives you've considered**
No other alternative exists, aside from manually updating kafka broker config.

**Additional context**
NA

**Comment by panyuenlau** [comment]
Hey @mahpatil, the operator allows one-way TLS/SSL authentication now, see this in the example `KafkaCluster`: https://github.com/banzaicloud/koperator/blob/master/config/samples/simplekafkacluster_ssl.yaml#L51-L52
