### ISSUE TITLE
Cruisecontrol deployment does not get recreated if deleted accidentally by user.

### ISSUE THREAD

**Issue by baluchicken** [banzaicloud/koperator#740]
**Describe the bug**
Cruisecontrol deployment does not get recreated if deleted accidentally by user.

**Steps to reproduce the issue:**
Create a simpleKafkacluster
Delete the cruise control deployment

**Expected behaviour**
CruiseControl deployment should be recreated immediately.

**Comment by Kuvesz** [comment]
Tried deleting the deployment and it got recreated so this issue was completely fixed by #749 .
