### ISSUE TITLE
CC capacity config fields does not gets updated with new broker fields

### ISSUE THREAD

**Issue by baluchicken** [banzaicloud/koperator#753]
**Describe the bug**
CC capacity config fields does not gets updated with new broker fields. The Operator will proceed thanks to the default value populated to the capacity.json but does not get updated when a new broker is added to the cluster. It means CC using the same resource values for all the brokers except for the initial cluster.

**Steps to reproduce the issue:**
Create a KafkaCluster using [SimpleKafkaCluster](https://github.com/banzaicloud/koperator/blob/master/config/samples/simplekafkacluster.yaml)
Add a broker to the cluster

**Expected behavior**
Capacity config should be up to date containing info from all brokers

**Comment by Kuvesz** [comment]
Could not reproduce the issue, please reopen if needed.
