### ISSUE TITLE
Pod priority support for kafkacluster, envoy and cruisecontrol through operator

### ISSUE THREAD

**Issue by raz08** [banzaicloud/koperator#772]
I did not find priorityClassName in kafkacluster CRD. Do we have pod priority support?. Is there a plan to add pod priority.

**Comment by panyuenlau** [comment]
@raz08 Thanks for bringing this up, we will add this support very soon

**Comment by panyuenlau** [comment]
@raz08 The `priorityClassName` field has been added to the `KafkaCluster` CRD for the broker, cruise control, and envoy pods, please refer to [this doc](https://github.com/banzaicloud/koperator/blob/master/config/samples/banzaicloud_v1beta1_kafkacluster.yaml) about how you can set this field in the CR
