### ISSUE TITLE
Kafka broker service is missing cluster labels

### ISSUE THREAD

**Issue by lavigne958** [banzaicloud/koperator#777]
**Describe the bug**
When creating a kafka cluster, we can request the operator to deploy a headless service or a broker service. 

When requesting a headless service, the created service metadata labels is filled with the kafka default labels and the labels from the kafkacluster resource.

When requesting a broker service, the created service metadata labels is only filled with the kafka default labels. Any labels that are set on the kafkaclsuter resource is not passed.

**Steps to reproduce the issue:**
Deploy a kafka cluster with the following spec:
```
KafkaCluster.Spec.HeadlessServiceEnabled: true
```

and some labels set like:
```
KafkaCluster.metadata.labels:
  - custom: myProduct
```

check the following field in the service `<kafkacluster name>-headless`

you will see the following labels in the generated service:
```
service.metadata.labels:
  - app: kafka
  - custom: myProduct
  - kafka_cr: <kafkacluster name>
```

Deploy a new kafka cluster without the headless service
```
KafkaCluster.Spec.HeadlessServiceEnabled: false
```

and some labels set like above
```
KafkaCluster.metadata.labels:
  - custom: myProduct
```

check the following field in the service `<kafkacluster name>-0`
```
service.metadata.labels:
  - app: kafka
  - kafka_cr: <kafkacluster name>
```

you won't see the labels that are set on the cluster

**Expected behavior**
I expected the labels that I set on the cluster to be set on the service too to I can filter the service using my custom labels I set, I can use the servicemonitor to target that service using my custom labels, I can ask my service monitor to read the labels of the service, those that are custom, and use them in all my metrics (this is mostly why I am here :slightly_smiling_face: )

**Screenshots**
no really

**Additional context**
I found where the changes would reside.

Here in the file `headlessService.go` we set the labels using the function `MergeLabels` and giving the standard labels and the labels from the kafkacluster resource.

https://github.com/banzaicloud/koperator/blob/e8c44e15d6aa9ebad2c5b46a0f4cf07a2edb67e3/pkg/resources/kafka/headlessService.go#L50

and here in the file `allBrokerService.go` we set the labels using the function `LabelsForKafka`
and only give the standards labels for kafkacluster, and we could use the above function that merge the kafkacluster labels and the standard labels

https://github.com/banzaicloud/koperator/blob/e8c44e15d6aa9ebad2c5b46a0f4cf07a2edb67e3/pkg/resources/kafka/allBrokerService.go#L40

This feature would be awesome if it's integrated into some future release, and it only add information and should be very safe to add (no breaking change) and very appreciated.

**Comment by stoader** [comment]
@lavigne958 have you tried `spec.propagateLabels: true` in your KafkaCluster CR?

**Comment by lavigne958** [comment]
Hi, no I did not know about this option, I will try that. Thanks for the quick answer :slightly_smiling_face:

**Comment by lavigne958** [comment]
Works like a charm thank you very much. 

Closing this issue.
