### ISSUE TITLE
Auto topic creation with default number of partitions and replicas

### ISSUE THREAD

**Issue by aakash10897** [banzaicloud/koperator#818]
**Describe the bug:**
Tried to set num.partitions and default.replication.factor at clusterWideConfig like this -
```
  clusterWideConfig: |
    num.partitions=12
    default.replication.factor=3
```

Also tried to set kafkaHeapOpts as described here-
https://github.com/banzaicloud/koperator/blob/master/docs/benchmarks/infrastructure/kafka.yaml

it didn't work !

**Comment by stoader** [comment]
Can you provide more details on what  do you mean by auto topic creation?

**Comment by stoader** [comment]
Closing this ticket as no repro steps were provided.
