### ISSUE TITLE
Document error about creating Prometheus-operator

### ISSUE THREAD

**Issue by kevin85421** [banzaicloud/koperator#825]
**Describe the bug**
The [document](https://banzaicloud.com/docs/supertubes/kafka-operator/install-kafka-operator/) indicates us to use the following command to create Prometheus-operator.

```bash
kubectl apply -n default -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/bundle.yaml
```

However, the command will occur the error `The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`.

Hence, the command on the document should be updated as follows.

```bash
kubectl create -n default -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/bundle.yaml
```

**Screenshots**
![截圖 2022-06-20 上午12 51 26](https://user-images.githubusercontent.com/20109646/174552519-8493e488-63dc-42c1-8094-8141b4e1f997.png)

**Comment by stoader** [comment]
Would you submit a PR with the corrected documentation?

**Comment by panyuenlau** [comment]
Closing this issue as it has been fixed
