### ISSUE TITLE
Enable Affinity for cruisecontrol through operator

### ISSUE THREAD

**Issue by karthiknagraj** [banzaicloud/koperator#844]
I did not find Affinity in kafkacluster CRD for cruisecontrol. Do we have Affinity support? Is there a plan to add Affinity? I see that affinity is added for envoyConfig and broker but it is not there for cruisecontrol.

**Comment by stoader** [comment]
@karthiknagraj currently only `spec.cruiseControlConfig.nodeSelector` is supported for deploying CC pod to specific nodes.

**Comment by bartam1** [comment]
Dear @karthiknagraj! Can you make a pull request for this change?

**Comment by karthiknagraj** [comment]
Sure, I can make a pull request. But I may need some help in testing it.

**Comment by bartam1** [comment]
Dear @karthiknagraj! We will review the PR and we will also make tests. Thank you!

**Comment by panyuenlau** [comment]
> Sure, I can make a pull request. But I may need some help in testing it.

@karthiknagraj, in addition to what has been mentioned by @bartam1, you can reach out to us via our [slack channel](https://community-banzaicloud.slack.com/#kafka-operator), where we can provide more detailed steps and feedback on testings

**Comment by panyuenlau** [comment]
Hey @karthiknagraj - this has been implemented by @shubhamcoc and will be available in our next release. Stay tuned!
