### ISSUE TITLE
Support Kafka 3.2.x

### ISSUE THREAD

**Issue by frankwg** [banzaicloud/koperator#852]
**Is your feature request related to a problem? Please describe.**
Apache Kafka 3.2.0 was out since May 17, 2022.
https://kafka.apache.org/downloads

**Describe the solution you'd like to see**
I‘d like to see Kafka 3.2.x is supported in Koperator

**Describe alternatives you've considered**
Where does the github repo host the Dockerfile of ghcr.io/banzaicloud/kafka image? If it's publicly available, I can build my own image with the desired version I want.

**Additional context**

**Comment by panyuenlau** [comment]
Hey @frankwg, thank you for bringing this up. We have Kafka 3.2 support in our internal project roadmap, unfortunately, we don't have a target date to release the Kafka 3.2 support yet

And yes, the Dockerfile that builds the kafka image is publicly available: https://github.com/banzaicloud/docker-kafka.

If would also be great if you are willing to help us test out Kafka 3.2 (and give us feedback on any issues that you see) after your build your own image for your needs

**Comment by panyuenlau** [comment]
Hey @frankwg - with https://github.com/banzaicloud/koperator/pull/1006, Koperator now supports up to Kafka 3.4.1. If you'd like to use any versions between 3.1.2 and 3.4.1, you can use https://github.com/banzaicloud/docker-kafka as a reference to build the appropriate version that feeds your need.
