### ISSUE TITLE
Allow exposing custom ports for kafka brokers

### ISSUE THREAD

**Issue by david-simon** [banzaicloud/koperator#897]
**Is your feature request related to a problem? Please describe.**
I have a custom kafka distribution that has an integrated metrics exporter service exposed as a HTTP service. I would like to have this port added to the container and the service specs.

**Describe the solution you'd like to see**
I would like to have a new field added to the CRD (probably with the corev1.ContainerPort type) that will be used to create the kafka containers and services

**Describe alternatives you've considered**
I tried adding an additional container that would proxy requests to the metrics api but then I have to also create a new service for each broker that exposes this port. This is not ideal since then I have to monitor the number of kafka brokers and adjust the services accordingly.

**Comment by hi-im-aren** [comment]
Hi @david-simon thanks for using koperator!

This seems like a good first issue so maybe you could contribute this to the project?

Also, could you think of some other scenarios where you think this could be useful for others as well?
The only thing that comes to my mind is some kind of remote debug port that can be used by this.

**Comment by david-simon** [comment]
Hi @hi-im-aren 
Sorry, forgot to mention in the description that I'm already working on this :)

I'll get back to you with some more use cases if I can

**Comment by david-simon** [comment]
Resolved in #898
