### ISSUE TITLE
kubebuilder/kube-rbac-proxy dockerfile cannot be found

### ISSUE THREAD

**Issue by jxjpds** [banzaicloud/koperator#899]
I did not find the kubebuilder/kube-rbac-proxy related dockerfile. I want to refer to this dockerfile.Please help me

**Comment by hi-im-aren** [comment]
Hi there, could you eloberate on what do you mean by `kubebuilder/kube-rbac-proxy related dockerfile`? What is exactly you are trying to achieve?

**Comment by jxjpds** [comment]
gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0    dockerfile.  I want to compile it to arm64.

**Comment by pregnor** [comment]
As readable in the image path that image is managed by the `kubebuilder` project on the Google container registry which is part of the Kubernetes 1st party team, https://github.com/banzaicloud/koperator has no relations or affiliations to them.

Looking at the public manifest of the 0.8.0 version of the image [here](https://console.cloud.google.com/gcr/images/kubebuilder/GLOBAL/kube-rbac-proxy@sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c/details?tag=v0.8.0&tab=pull) there is already a `linux/arm64` image built from it in a multi-architecture fashion.

If you still require assistance regarding that Dockerfile, please contact the Kubebuilder team at https://github.com/kubernetes-sigs/kubebuilder/.
