### ISSUE TITLE
Inconsistent input expectations for .Values.imagePullSecrets

### ISSUE THREAD

**Issue by cotej** [banzaicloud/koperator#999]
## Description

The kafka-operator helm chart allows for an input value `imagePullSecrets` as defined here:
https://github.com/banzaicloud/koperator/blob/6871af2c13c68d810ea32493736c0060b6f40124/charts/kafka-operator/values.yaml#L8

In the template for the operator `Deployment`, there is an expectation that this should hold an array of objects which can be directly rendered to yaml here:
https://github.com/banzaicloud/koperator/blob/6871af2c13c68d810ea32493736c0060b6f40124/charts/kafka-operator/templates/operator-deployment-with-webhook.yaml#L140

This would suggest to use an input value that looks something like (**Example A**):
```yaml
imagePullSecrets:
  - name: my-img-pull-secret
  - name: another-img-pull-secret
```

However, in the template for authproxy `ServiceAccount`, it attempts to use this value as if it is an array of simple strings:
https://github.com/banzaicloud/koperator/blob/6871af2c13c68d810ea32493736c0060b6f40124/charts/kafka-operator/templates/authproxy-rbac.yaml#L5

Which suggests that the input value should rather look like (**Example B**):
```yaml
imagePullSecrets:
  - my-img-pull-secret
  - another-img-pull-secret
```

## Expected Behavior

The usage of this value should be consistent across all templates of the chart.

## Actual Behavior

If you attempt to install the chart with a value like **Example B** above, an error is encountered.

The chart will successfully install when using a value like **Example A**, _however_ it ends up rendering some incorrect yaml on the authproxy `ServiceAccount`, which ends up looking like:
```yaml
apiVersion: v1
imagePullSecrets:
- name: map[name:my-img-pull-secret]
kind: ServiceAccount
...
```

## Affected Version

kafka-operator chart version **0.24.1**

## Steps to Reproduce

See examples given above.

## Checklist

- [x] I have read the [contributing guidelines](../CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by panyuenlau** [comment]
Thanks for reporting this, @cotej! It'd be greatly appreciated if you can come up with a PR for fixing the chart.
